/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-10-17 11:47:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adhyayan_002dsarthi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Adhyayan Sarthi</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/styles/AdhyayanSarthi.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon (1) (1).png\" type=\"image/x-icon\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("	<!--     <nav id=\"navbar\">\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("            <img src=\"logo.png\" alt=\"TastyMealzz.com\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"item\"><a href=\"#home\">Home</a></li>\r\n");
      out.write("            <li class=\"item\"><a href=\"#services-container\">Services</a></li>\r\n");
      out.write("            <li class=\"item\"><a href=\"#client-section\">Our Clients</a></li>\r\n");
      out.write("            <li class=\"item\"><a href=\"#contact\">Contact Us</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav> -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"wel\">\r\n");
      out.write("				<h1>WELCOME TO ADHYAYAN SARTHI !</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<img src=\"favicon (1) (1).png\" alt=\"AdhyayanSarthi\"\r\n");
      out.write("				class=\"background\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"foreground\">\r\n");
      out.write("				<img src=\"anand-removebg-preview.png\" alt=\"AdhyayanSarthi\"\r\n");
      out.write("					class=\"image\">\r\n");
      out.write("				<pre class=\"intro\">\r\n");
      out.write("                    Anand Kumar Pandey,\r\n");
      out.write("                    BTech, NIT-Bhopal\r\n");
      out.write("                    Faculty- Mathematics\r\n");
      out.write("                </pre>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"foreground\">\r\n");
      out.write("				<img src=\"1670033747690-removebg-preview.png\" alt=\"AdhyayanSarthi\"\r\n");
      out.write("					class=\"image\">\r\n");
      out.write("				<pre class=\"intro\">\r\n");
      out.write("                    Nilesh Modi,\r\n");
      out.write("                    BTech, NIT-Bhopal\r\n");
      out.write("                    Faculty- Chemistry\r\n");
      out.write("                </pre>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"foreground\">\r\n");
      out.write("				<img src=\"anuj1-removebg-preview.png\" alt=\"AdhyayanSarthi\"\r\n");
      out.write("					class=\"image\">\r\n");
      out.write("				<pre class=\"intro\">\r\n");
      out.write("                    Anuj Singh Rajawat,\r\n");
      out.write("                    BTech, RGPV-Bhopal\r\n");
      out.write("                    Faculty- Physics\r\n");
      out.write("                </pre>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<section>\r\n");
      out.write("			<h2 class=\"about\">About</h2>\r\n");
      out.write("			<p class=\"text\">\r\n");
      out.write("				Adhyayan Saarthi is a comprehensive student support platform\r\n");
      out.write("				dedicated to empowering students in every facet of their academic\r\n");
      out.write("				journey. Our primary objective is to provide unparalleled assistance\r\n");
      out.write("				to students by offering a wide range of services, including\r\n");
      out.write("				personalized career guidance, expert consulting, valuable insights\r\n");
      out.write("				into various career paths, access to scholarships and financial aid\r\n");
      out.write("				opportunities, and much more. With a deep commitment to student\r\n");
      out.write("				success, Adhyayan Saarthi strives to be a trusted companion, guiding\r\n");
      out.write("				students towards achieving their educational and professional\r\n");
      out.write("				aspirations. <br>\r\n");
      out.write("				<br>\r\n");
      out.write("			</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bg bg1\">\r\n");
      out.write("				<h2 class=\"desc\">SCHOLARSHIPS</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"text\">\r\n");
      out.write("				At Adhyayan Saarthi, we provide comprehensive and detailed\r\n");
      out.write("				information about scholarships available in Madhya Pradesh (MP). Our\r\n");
      out.write("				dedicated team researches and presents the eligibility criteria,\r\n");
      out.write("				application processes, deadlines, and necessary documentation for\r\n");
      out.write("				various scholarships. We also offer personalized guidance to help\r\n");
      out.write("				students navigate the scholarship application process effectively.\r\n");
      out.write("				Our goal is to make scholarship opportunities in MP more accessible\r\n");
      out.write("				and empower students to pursue their educational goals without\r\n");
      out.write("				financial barriers. <br>\r\n");
      out.write("				<br> By offering in-depth information about scholarships in\r\n");
      out.write("				Madhya Pradesh, we aim to bridge the information gap and make the\r\n");
      out.write("				scholarship search process more accessible and less overwhelming for\r\n");
      out.write("				students. We believe that every deserving student should have the\r\n");
      out.write("				opportunity to pursue their educational goals without financial\r\n");
      out.write("				constraints, and we are here to help them navigate the scholarship\r\n");
      out.write("				landscape in MP with confidence and success.\r\n");
      out.write("			</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bg bg2\">\r\n");
      out.write("				<h2 class=\"desc\">CAREER GUIDANCE</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"text\">\r\n");
      out.write("				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed\r\n");
      out.write("				vehicula nisi eget nisl interdum, sed posuere dolor feugiat. Fusce\r\n");
      out.write("				euismod dictum nisl, in tincidunt arcu. Donec nec libero vitae purus\r\n");
      out.write("				venenatis malesuada. Sed tempus elementum elit, nec blandit leo\r\n");
      out.write("				congue eu. Donec non dui at libero facilisis auctor. Fusce nec lacus\r\n");
      out.write("				at lectus tincidunt tristique in a metus. Aenean sit amet dolor nec\r\n");
      out.write("				ex volutpat blandit. Vestibulum placerat vel est at tincidunt. <br>\r\n");
      out.write("				<br>\r\n");
      out.write("			</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bg bg3\">\r\n");
      out.write("				<h2 class=\"desc\">EXPERT CONSULTING</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"text\">\r\n");
      out.write("				Our expert consulting services are designed to guide students\r\n");
      out.write("				through the complexities of career planning and educational choices.\r\n");
      out.write("				We understand that choosing the right career path and academic\r\n");
      out.write("				institution can be overwhelming, and we aim to simplify this process\r\n");
      out.write("				for students. Our team of experienced consultants offers\r\n");
      out.write("				personalized advice and insights based on the individual needs and\r\n");
      out.write("				aspirations of students. Whether you are looking for guidance on\r\n");
      out.write("				course selection, career options, or educational institutions, our\r\n");
      out.write("				experts are here to assist you. <br>\r\n");
      out.write("				<br>\r\n");
      out.write("			</p>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"client-section\" id=\"client-section\">\r\n");
      out.write("		<h2 class=\"client\">Our Clients</h2>\r\n");
      out.write("		<p class=\"text\">At Adhyayan Saarthi, our clients are our most\r\n");
      out.write("			valuable assets. We are committed to delivering exceptional services\r\n");
      out.write("			that meet their unique needs and preferences. Here are some of the\r\n");
      out.write("			clients who have put their trust in us.</p>\r\n");
      out.write("		<div class=\"client-list\">\r\n");
      out.write("			<img src=\"client1.png\" alt=\"Client 1\" class=\"client-img\"> <img\r\n");
      out.write("				src=\"client2.png\" alt=\"Client 2\" class=\"client-img\"> <img\r\n");
      out.write("				src=\"client3.png\" alt=\"Client 3\" class=\"client-img\"> <img\r\n");
      out.write("				src=\"client4.png\" alt=\"Client 4\" class=\"client-img\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"contact\" id=\"contact\">\r\n");
      out.write("		<h2 class=\"contact-title\">Contact Us</h2>\r\n");
      out.write("		<div class=\"contact-form\">\r\n");
      out.write("			<form action=\"/springmvc/contact\" method=\"POST\">\r\n");
      out.write("				<label for=\"name\">Name:</label> <input type=\"text\" id=\"name\"\r\n");
      out.write("					name=\"name\" required> <label for=\"email\">Email:</label> <input\r\n");
      out.write("					type=\"email\" id=\"email\" name=\"email\" required> <label\r\n");
      out.write("					for=\"message\">Message:</label>\r\n");
      out.write("				<textarea id=\"message\" name=\"message\" required></textarea>\r\n");
      out.write("\r\n");
      out.write("				<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<p>&copy; 2023 Adhyayan Sarthi. All rights reserved.</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
